Repository tomochain/tomochain, pull requests merged in 2018-08, with the labels that each got.

#111 extend timeout to 10s
  miner/worker.go
Labels: review

#113 Add signers and finality to block status api.
  cmd/tomo/main.go
  consensus/clique/clique.go
  contracts/blocksigner/blocksigner_test.go
  contracts/blocksigner/contract/BlockSigner.sol
  contracts/blocksigner/contract/blocksigner.go
  contracts/utils_test.go
  core/blockchain.go
  eth/api_backend.go
  eth/backend.go
  internal/ethapi/api.go
  internal/ethapi/backend.go
  les/api_backend.go
Labels: review

#120 Fixed finality using percent instead of boolean value for block status
  internal/ethapi/api.go
Labels: review

#124 update Tomo Validator smart contract, add getWithdrawCap function
  contracts/validator/contract/TomoValidator.sol
  contracts/validator/contract/validator.go
Labels: review

#116 hotfix: signed recently issue
  consensus/clique/clique.go
Labels: review

#129 Fixed div by zero for calculate reward.
  contracts/utils.go
Labels: review

#128 Fixed prevent tx zero gas price add to tx pool.
  core/tx_pool.go
  core/tx_pool_test.go
Labels: review

#131 Fix bug unvote in smart contract
  contracts/validator/contract/TomoValidator.sol
  contracts/validator/contract/validator.go
Labels: review

#134 remove nodeId in smart contract
  contracts/validator/contract/TomoValidator.sol
  contracts/validator/contract/interfaces/IValidator.sol
  contracts/validator/contract/validator.go
  contracts/validator/validator_test.go
Labels: review

#132 directly set mns to snapshot
  consensus/clique/clique.go
  internal/ethapi/api.go
  miner/worker.go
Labels: review

#136 Fixed reward overflow uint64.
  eth/backend.go
Labels: review

#138 Chuck size importing
  consensus/clique/clique.go
  eth/downloader/downloader.go
Labels: review

#142 declare alpha version
  params/version.go
Labels: review

#143 remove duplicated import
  internal/ethapi/api.go
Labels: review

#141 Fixed move foundation wallet address to genesis config.
  cmd/puppeth/wizard_genesis.go
  cmd/utils/flags.go
  consensus/posv/posv.go
  consensus/posv/snapshot.go
  contracts/utils.go
  contracts/validator/validator_test.go
  eth/backend.go
  eth/downloader/downloader_test.go
  internal/ethapi/api.go
  internal/web3ext/web3ext.go
  les/odr_test.go
  les/request_test.go
  miner/worker.go
  params/config.go
  params/version.go
Labels: review

#145 prepare contract, genesis
  cmd/puppeth/wizard_genesis.go
  contracts/validator/contract/TomoValidator.sol
  contracts/validator/contract/validator.go
  contracts/validator/validator.go
Labels: review

#146 Genesis
  genesis/devnet.json
  genesis/testnet.json
Labels: review

#147 bug genesis
  contracts/validator/validator.go
  genesis/devnet.json
  genesis/testnet.json
Labels: review

#148 add minvotercap
  contracts/validator/contract/TomoValidator.sol
  contracts/validator/contract/validator.go
  contracts/validator/validator.go
  contracts/validator/validator_test.go
  genesis/devnet.json
  genesis/testnet.json
Labels: review

#149 decode again value from rlp
  cmd/puppeth/wizard_genesis.go
Labels: review

#152 update .travis.yml
  .travis.yml
Labels: CI/CD, review

#154 update .travis.yml
  .travis.yml
Labels: CI/CD, review

#157 fix update m1 when import data
  cmd/tomo/main.go
  consensus/clique/snapshot_test.go
  consensus/posv/posv.go
  consensus/posv/snapshot_test.go
  core/blockchain.go
  eth/backend.go
  eth/downloader/downloader.go
  eth/downloader/downloader_test.go
Labels: review

#102 Move argument from flags to config file
  cmd/tomo/chaincmd.go
  cmd/tomo/config.go
  cmd/tomo/consolecmd.go
  cmd/tomo/main.go
  cmd/tomo/testdata/config.toml
Labels: backlog

#155 Disable function send transaction with rpc
  rpc/server.go
Labels: review
