Repository tomochain/tomochain, pull requests merged in 2018-07, with the labels that each got.

#96 Add pipeline for tagged release
  .travis.yml
  docker_push.sh
Labels: CI/CD

#107 Update .travis.yml
  docker_push.sh
  docker_rebuild.sh
Labels: CI/CD

#108 move gap into genesis config
  cmd/puppeth/wizard_genesis.go
  core/blockchain.go
  miner/worker.go
  params/config.go
Labels: review

#109 Hotfix broken travis deployment
  .travis.yml
  docker_push.sh
  docker_rebuild.sh
Labels: CI/CD, bug, review

#110 Hotfix travis conditions
  .travis.yml
Labels: CI/CD, bug, review

#103 clean up Makefile
  .travis.yml
  Makefile
  VERSION
  build/ci.go
  build/deb.changelog
  build/deb.control
  build/deb.copyright
  build/deb.docs
  build/deb.install
  build/deb.rules
  build/mvn.pom
  build/mvn.settings
  build/nsis.envvarupdate.nsh
  build/nsis.geth.nsi
  build/nsis.install.nsh
  build/nsis.pathupdate.nsh
  build/nsis.simplefc.dll
  build/nsis.simplefc.source.zip
  build/nsis.uninstall.nsh
  build/pod.podspec
  build/update-license.go
  internal/build/archive.go
  internal/build/azure.go
  internal/build/pgp.go
  internal/build/util.go
Labels: backlog
